<?xml version='1.0'?>

<robot name="quantum" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="cameraSize" value="0.05"/>
  <xacro:property name="cameraMass" value="0.1"/>
  <xacro:property name="wheelradius" value="0.174"/>
  <xacro:property name="wheelwidth" value="0.095"/>
  <xacro:property name="wheelDistance" value="0.54"/>
  <xacro:property name="bodyLength" value="0.80"/>
  <xacro:property name="casterRadius" value="0.05"/>


  <xacro:include filename="$(find tobor_description)/urdf/tobor.gazebo" />
  <xacro:include filename="$(find tobor_description)/urdf/materials.xacro" />
  <xacro:include filename="$(find tobor_description)/urdf/macros.xacro" />

  <link name='base_link'>
    <pose>0 0 0.1 0 0 0</pose>
    
    <collision name='collision'>
      <origin xyz="-.2 0 0" rpy=" 0 0 0"/>
      <geometry>
        <box size=".78 .43 .05"/>
      </geometry>
    </collision>
    <visual name='base_link_visual'>
      <origin xyz="-.2 0 0" rpy=" 0 0 0"/>
      <geometry>
        <box size=".78 .43 .05"/>
      </geometry>
    </visual>

    <collision name='left_caster_collision'>
      <origin xyz="-0.50 -0.15 -${wheelradius-casterRadius}" rpy=" 0 0 0"/>
      <geometry>
        <sphere radius="${casterRadius}"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>0</mu>
            <mu2>0</mu2>
          </ode>
        </friction>
      </surface>
    </collision>
    <visual name='left_caster_visual'>
      <origin xyz="-0.50 -0.15 -0.12" rpy=" 0 0 0"/>
      <geometry>
        <sphere radius="${casterRadius}"/>
      </geometry>
    </visual>

    <collision name='right_caster_collision'>
        <origin xyz="-0.50 0.15 -0.12" rpy=" 0 0 0"/>
        <geometry>
          <sphere radius="${casterRadius}"/>
        </geometry>
        <surface>
          <friction>
            <ode>
              <mu>0</mu>
              <mu2>0</mu2>
            </ode>
          </friction>
        </surface>
      </collision>
    <visual name='right_caster_visual'>
      <origin xyz="-0.50 0.15 -0.12" rpy=" 0 0 0"/>
      <geometry>
        <sphere radius="${casterRadius}"/>
      </geometry>
    </visual>
  </link>


  <link name="left_wheel">
    <!--origin xyz="0.1 0.13 0.1" rpy="0 1.5707 1.5707"/-->
    <collision name="collision">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
         <cylinder radius="${wheelradius}" length="${wheelwidth}"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>30</mu>
            <mu2>30</mu2>
            <slip1>1.0</slip1>
            <slip2>1.0</slip2>
          </ode>
        </friction>
      </surface>
    </collision>
    <visual name="left_wheel_visual">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="${wheelradius}" length="${wheelwidth}"/>
      </geometry>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <mass value="5"/>
      <inertia
        ixx=".1" ixy="0.0" ixz="0.0"
        iyy=".1" iyz="0.0"
        izz=".1"/>
    </inertial>
  </link>

  <link name="right_wheel">
    <!--origin xyz="0.1 -0.13 0.1" rpy="0 1.5707 1.5707"/-->
    <collision name="collision">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="${wheelradius}" length="${wheelwidth}"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>30</mu>
            <mu2>30</mu2>
            <slip1>1.0</slip1>
            <slip2>1.0</slip2>
          </ode>
        </friction>
      </surface>
    </collision>
    <visual name="right_wheel_visual">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="${wheelradius}" length="${wheelwidth}"/>
      </geometry>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <mass value="5"/>
      <inertia
        ixx=".1" ixy="0.0" ixz="0.0"
        iyy=".1" iyz="0.0"
        izz=".1"/>
    </inertial>
  </link>


  <joint type="continuous" name="left_wheel_hinge">
    <origin xyz="0.0 0.27 0" rpy="0 0 0"/>
    <!--origin xyz="0.1 0.13 0" rpy="0 1.5707 1.5707"/-->
    <child link="left_wheel"/>
    <parent link="base_link"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <joint_properties damping="1.0" friction="1.0"/>
  </joint>

  <joint type="continuous" name="right_wheel_hinge">
    <origin xyz="0.0 -0.27 0" rpy="0 0 0"/>
    <!--origin xyz="0.1 -0.13 0" rpy="0 1.5707 1.5707"/-->
    <child link="right_wheel"/>
    <parent link="base_link"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <joint_properties damping="1.0" friction="1.0"/>
  </joint>

  <link name="body">
    <!--origin xyz="0.1 -0.13 0.1" rpy="0 1.5707 1.5707"/-->
    <collision name="collision">
      <origin xyz="-.2 0 0.1" rpy=" 0 0 0"/>
      <geometry>
        <box size=".78 .43 .35"/>
      </geometry>
    </collision>
    <visual name="right_wheel_visual">
      <origin xyz="-.2 0 0.3" rpy=" 0 0 0"/>
      <geometry>
        <box size=".78 .43 .35"/>
      </geometry>
      <material name="yellow"/>
    </visual>
   <inertial>
      <mass value="5.0"/>
      <origin xyz="-.2 0 0" rpy=" 0 0 0"/>
      <inertia
          ixx="0.0937" ixy="0" ixz="0"
          iyy="0.27" iyz="0"
          izz="0.33"
      />
    </inertial>
  </link>

  <joint type="fixed" name="body_hinge">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <!--origin xyz="0.1 -0.13 0" rpy="0 1.5707 1.5707"/-->
    <child link="body"/>
    <parent link="base_link"/>
    <axis xyz="0 0 0" rpy="0 0 0"/>
  </joint>



  <link name="camera">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
      </geometry>
      <material name="green"/>
    </visual>

    <inertial>
      <mass value="${cameraMass}" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <box_inertia m="${cameraMass}" x="${cameraSize}" y="${cameraSize}" z="${cameraSize}" />
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  <joint name="camera_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz=".2 0 .2" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="camera"/>
  </joint>


  <joint name="hokuyo_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz=".2 0 .3" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="hokuyo"/>
  </joint>

  
  <link name="hokuyo">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
    <box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://tobor_description/meshes/hokuyo.dae"/>
      </geometry>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  


</robot>

